# Site settings
title: Tyler Pugmire | Software Engineer
description: Tyler Pugmire | Software Engineer
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tyler-pugmire.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Tyler Pugmire
user_description: I graduated from DigiPen Institute of Technology with a Bachelor of Science in Computer Science in Real-Time Interactive Simulation.
user_title: Software Developer
email: tyler.p@digipen.edu
twitter_username: Tyler_Pugmire
github_username:  tyler-pugmire
gplus_username:  lorem_ipsum
youtube_username: TheTylersaurusrex

# Google-analytics
google-analytics:
  id: "UA-111860466-1"

exclude: ['package.json', 'src' , 'node_modules']

include: ['_pages']
